### ISSUE TITLE
Boolean module parameter formatting differs from HubL documentation

### ISSUE THREAD

**Issue by evelynn-causemic** [HubSpot/prettier-plugin-hubl#44]
## Description

When formatting templates which include modules via the `{% module %}` tag, boolean parameters (such as `export_to_template_context`) are formatted in a way which is inconsistent with the HubL documentation.

### Expected behavior

Boolean values are formatted as found in the HubL documentation—capitalized, and do not have containing quotes.
`{% module "module_name" [...] boolean_param=True %}`

### Observed behavior
Formatted boolean values are contained within quotes and lowercase.  
`{% module "module_name" [...] boolean_param="true" %}`

## Additional context

I haven't confirmed to what extent (if any) this _actually_ poses any issues with compatibility or functionality. If someone more knowledgeable in the deep magicks of HubL can confirm that formatting boolean values like strings won't produce any edge/corner-case weirdness, I'm of the personal opinion that the current behavior produces a more readable output.

**Comment by anthmatic** [comment]
I'm actually not able to reproduce this yet. A tag like `{% module "module_name" export_to_template_context=True %}` produces: 
```
  {% module "module_name"
    export_to_template_context=True %}
```
which is the expected output. 

@evelynn-causemic can you confirm that you're using the latest version `0.2.4`? (It might be easiest to check `node_modules/@hubspot/prettier-plugin-hubl/package.json` for a version number)  

If so, any Prettier configs or specific code examples would be helpful to keep debugging. It's possible that things my continue to work for you with/without quotes but I would expect this plugin to keep values the same when formatting.
