### ISSUE TITLE
Bracket notation will be reformatted even when dot notation is invalid

### ISSUE THREAD

**Issue by evelynn-causemic** [HubSpot/prettier-plugin-hubl#70]
## Description

When accessing an object value using bracket notation, it will always be reformatted into dot notation, even if the key contains characters that are not valid in dot notation.

## Expected behavior

Bracket notation should not be reformatted to use dot notation if the key contains spaces or other invalid characters.

### Original Source Code:
This will successfully print the value "baz".
```jinja2
{% set test_object = {
    "foo bar": "baz"
}%}
{{ test_object["foo bar"] }}
```

### Formatted Source Code:
This will not print the value inside the object, and will present an error.
```jinja2
{% set test_object = {
    "foo bar": "baz"
}%}
{{ test_object.foo bar }}
```

## Notes

As a matter of opinion, I'm not convinced that it's sensible to unilaterally enforce dot notation. While it is typically more readable, bracket notation can do some things that dot notation simply cannot (for example: text interpolation inside key values, accessing values whose keys contain syntactically significant characters). Without the ability to selectively disable formatting, this aggressive formatting rule effectively locks you out of that functionality.

## Checklist

- [x] I have checked the [known issues](https://github.com/HubSpot/prettier-plugin-hubl/issues/18) to make sure this isn’t already a known issue.

**Comment by j-malt** [comment]
Hi Evelynn. Thank you for the report. This is fixed in #77 and should be released in the next version of the plugin.
