### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by EmilioHerreraSoukup** [HubSpot/prettier-plugin-hubl#73]
**Description**

Apologies for reporting this as a bug, but just wanted to know the status of the project, as last commit was 2 years ago. Thanks!

**Comment by TanyaScales** [comment]
Hello! This project is _not_ abandoned -- However, it fell into a bit of a stale state where any active work was placed in an icebox. We are starting to look through some of the reported bugs and remaining issues in this repo. There should be some updates coming shortly. We do not have any major feature work/enhancements planned outside of this for the near future. Thanks for reaching out.
