### ISSUE TITLE
Are you cutting a new release?

### ISSUE THREAD

**Issue by happycollision** [HubSpot/prettier-plugin-hubl#79]
I see that you've got several PRs merged this year, but nothing new has been released to NPM. Is that intentional? I'd love to move our codebase off of [the fork I created to support Prettier v3](https://github.com/HubSpot/prettier-plugin-hubl/issues/75#issuecomment-2092043028) if you all are planning on releasing it.

![CleanShot 2024-10-23 at 16 32 31@2x](https://github.com/user-attachments/assets/3f8d8fa9-4678-4af2-9c6f-108de682216d)

**Comment by thirdender** [comment]
I would appreciate a new release as well. I'm running a local copy of HEAD and it's working well for my purposes, solves many outstanding issues from the last release (including numerical indexes being stripped #68).

**Comment by TanyaScales** [comment]
A new version has been released to the [beta](https://www.npmjs.com/package/@hubspot/prettier-plugin-hubl/v/0.3.2) -- we're looking to iterate on the way this is being packaged and so we'll be keeping this on the beta for now.
